server:
    port: 8088
    contextPath: /

spring:
    profiles:
        active: spring.profiles.active

security:
    basic:
        enabled: true
    oauth2:
        client:
            clientId:  1063162516111-i71njaprmseo8gvi1rnk0tbaiks8lpgu.apps.googleusercontent.com
            clientSecret: ouIrwWzFFc6t1fZQbJfQWuvP
            accessTokenUri: https://www.googleapis.com/oauth2/v3/token
            userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
            tokenName: oauth_token
            authenticationScheme: query
            clientAuthenticationScheme: form
            scope: profile
        resource:
            userInfoUri: https://www.googleapis.com/userinfo/v2/me
            preferTokenInfo: false
