server:
    port: 8088
    contextPath: /

spring:
    profiles:
        active: spring.profiles.active

security:
    basic:
        enabled: true
    oauth2:
        client:
            clientId: 110126017402352537348
            clientSecret: e616aceb1db25dc6eee6ffdaa23fdf1ee8c1108c
            accessTokenUri: https://www.googleapis.com/oauth2/v3/token
            userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
            tokenName: oauth_token
            authenticationScheme: query
            clientAuthenticationScheme: form
            scope: profile
        resource:
            userInfoUri: https://www.googleapis.com/userinfo/v2/me
            preferTokenInfo: false
